# ============================================================================
# 游냡 Docker Compose para Minecraft Fabric Server
# Versi칩n: 3.8
# Prop칩sito: Orquestaci칩n completa del servidor con servicios auxiliares
# ============================================================================

version: '3.8'

services:
  # === SERVIDOR MINECRAFT FABRIC ===
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MINECRAFT_VERSION: "1.20.4"
        FABRIC_VERSION: "0.15.6"
        FABRIC_INSTALLER_VERSION: "0.11.2"
    container_name: minecraft-fabric-server
    hostname: minecraft-server
    restart: unless-stopped
    
    # Variables de entorno
    environment:
      # Configuraci칩n del servidor
      - EULA=false  # Cambiar a true para aceptar EULA autom치ticamente
      - SERVER_PORT=25565
      - MAX_PLAYERS=20
      - DIFFICULTY=normal
      - GAMEMODE=survival
      - LEVEL_NAME=world
      - MOTD=춶6춰Servidor Fabric con Docker!춶r
      
      # Configuraci칩n Java (ajustar seg칰n RAM disponible)
      - JAVA_OPTS=-Xmx2G -Xms2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
      
      # Configuraci칩n de zona horaria
      - TZ=America/Mexico_City
    
    # Puertos expuestos
    ports:
      - "25565:25565"  # Puerto principal del servidor
      - "25575:25575"  # Puerto RCON (opcional)
    
    # Vol칰menes para persistencia
    volumes:
      # Mundo del servidor (persistente)
      - minecraft_world:/opt/minecraft/server/world
      
      # Mods (persistente para actualizaciones manuales)
      - minecraft_mods:/opt/minecraft/server/mods
      
      # Backups autom치ticos
      - minecraft_backups:/opt/minecraft/backups
      
      # Configuraci칩n del servidor (persistente)
      - minecraft_config:/opt/minecraft/server/config
      
      # Logs del servidor
      - minecraft_logs:/opt/minecraft/server/logs
      
      # Archivo de configuraci칩n (opcional - para personalizaci칩n avanzada)
      # - ./server.properties:/opt/minecraft/server/server.properties:ro
      
      # Whitelist y ops (opcional)
      # - ./whitelist.json:/opt/minecraft/server/whitelist.json
      # - ./ops.json:/opt/minecraft/server/ops.json
    
    # Configuraci칩n de recursos
    deploy:
      resources:
        limits:
          memory: 3G      # L칤mite de memoria (ajustar seg칰n necesidades)
          cpus: '2.0'     # L칤mite de CPU (ajustar seg칰n cores disponibles)
        reservations:
          memory: 1G      # Memoria reservada m칤nima
          cpus: '0.5'     # CPU reservada m칤nima
    
    # Pol칤tica de reinicio
    restart: unless-stopped
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Redes
    networks:
      - minecraft-network
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Dependencias (servicios que deben iniciarse antes)
    depends_on:
      - minecraft-backup

  # === SERVICIO DE BACKUP AUTOM츼TICO ===
  minecraft-backup:
    image: alpine:latest
    container_name: minecraft-backup-service
    restart: unless-stopped
    
    environment:
      - TZ=America/Mexico_City
      - BACKUP_INTERVAL=24h    # Intervalo de backup (24h = cada d칤a)
      - BACKUP_RETENTION=7     # D칤as de retenci칩n de backups
    
    volumes:
      - minecraft_world:/data/world:ro  # Solo lectura para backup
      - minecraft_mods:/data/mods:ro
      - minecraft_config:/data/config:ro
      - minecraft_backups:/backups
    
    command: >
      sh -c "
      apk add --no-cache tar gzip &&
      while true; do
        echo '[$(date)] Creando backup autom치tico...'
        tar -czf /backups/minecraft_backup_$(date +%Y%m%d_%H%M%S).tar.gz -C /data .
        echo '[$(date)] Backup creado exitosamente'
        find /backups -name '*.tar.gz' -mtime +$$BACKUP_RETENTION -delete
        echo '[$(date)] Backups antiguos limpiados'
        sleep $$BACKUP_INTERVAL
      done"
    
    networks:
      - minecraft-network

  # === SERVICIO DE MONITOREO (OPCIONAL) ===
  minecraft-monitor:
    image: alpine:latest
    container_name: minecraft-monitor
    restart: unless-stopped
    
    environment:
      - TZ=America/Mexico_City
      - MONITOR_INTERVAL=60s   # Intervalo de monitoreo
    
    volumes:
      - minecraft_logs:/logs:ro
      - minecraft_backups:/monitoring
    
    command: >
      sh -c "
      apk add --no-cache curl &&
      while true; do
        echo '[$(date)] === ESTADO DEL SERVIDOR ===' > /monitoring/status.log
        echo 'Timestamp: $(date)' >> /monitoring/status.log
        echo 'Container Status: OK' >> /monitoring/status.log
        if [ -f /logs/latest.log ]; then
          echo 'Log Size: $(stat -f%z /logs/latest.log 2>/dev/null || stat -c%s /logs/latest.log)' >> /monitoring/status.log
          echo 'Last Log Lines:' >> /monitoring/status.log
          tail -5 /logs/latest.log >> /monitoring/status.log 2>/dev/null || echo 'No logs available' >> /monitoring/status.log
        fi
        echo '================================' >> /monitoring/status.log
        sleep $$MONITOR_INTERVAL
      done"
    
    networks:
      - minecraft-network
    
    depends_on:
      - minecraft-server

# === CONFIGURACI칍N DE VOL칔MENES ===
volumes:
  # Mundo del servidor (datos m치s importantes)
  minecraft_world:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/world
  
  # Mods del servidor
  minecraft_mods:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mods
  
  # Backups autom치ticos
  minecraft_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backups
  
  # Configuraciones
  minecraft_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/config
  
  # Logs del servidor
  minecraft_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs

# === CONFIGURACI칍N DE REDES ===
networks:
  minecraft-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16